services:
  labyrinth:
    image: labyrinth_image_dev
    build:
      context: .
    container_name: labyrinth_app_dev
    depends_on:
      - dev_db
    env_file:
      - .env
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - 8000:8000
    volumes:
      - ../backend:/app/backend
  
  dev_db:
    image: postgres:16.4
    container_name: labyrinth_db_dev
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - lab_data:/var/lib/postgresql/data

volumes:
  lab_data: