services:
  labyrinth:
    image: labyrinth_image_dev
    build:
      context: ..
      dockerfile: dev/Dockerfile
    container_name: labyrinth_app_dev
    depends_on:
      - dev_db
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    command: ["/app/scripts/app.sh"]
    ports:
      - 7777:8000
    volumes:
      - ../backend:/app/backend
      - ../dev/migrations:/app/dev/migrations
  
  dev_db:
    image: postgres:16.4
    container_name: labyrinth_db_dev
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - lab_data:/var/lib/postgresql/data

volumes:
  lab_data: