build:
	docker compose build

up:
	docker compose up

down:
	docker compose down

build-up:
	docker compose up --build

psql:
	docker exec -it labyrinth_db_dev psql -U dev -d labyrinth_dev

in_app:
	docker exec -it labyrinth_app_dev /bin/bash

in_db:
	docker exec -it labyrinth_db_dev /bin/bash